// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iti_DB_forms.Models;

[Index("Top_Id", Name = "IX_Courses_Top_Id")]
public partial class Course
{
    [Key]
    public int Crs_Id { get; set; }

    public string Crs_Name { get; set; }

    public int? Duration { get; set; }

    public int? Top_Id { get; set; }

    [InverseProperty("Crs")]
    public virtual ICollection<Ins_Cource> Ins_Cources { get; set; } = new List<Ins_Cource>();

    [InverseProperty("Crs")]
    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();

    [ForeignKey("Top_Id")]
    [InverseProperty("Courses")]
    public virtual Topic Top { get; set; }
}