// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iti_DB_forms.Models;

public partial class Department
{
    [Key]
    public int Dept_Id { get; set; }

    public string Dept_Name { get; set; }

    public string Dept_Desc { get; set; }

    public string Dept_Location { get; set; }

    public int? Dept_Maneger { get; set; }

    public DateTime? Maneger_Hiredate { get; set; }

    [ForeignKey("Dept_Maneger")]
    [InverseProperty("Department")]
    public virtual Instructor Dept_ManegerNavigation { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}