// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iti_DB_forms.Models;

[PrimaryKey("Crs_Id", "Ins_Id")]
[Index("Ins_Id", Name = "IX_Ins_Cources_Ins_Id")]
public partial class Ins_Cource
{
    [Key]
    public int Ins_Id { get; set; }

    [Key]
    public int Crs_Id { get; set; }

    public string Evaluation { get; set; }

    [ForeignKey("Crs_Id")]
    [InverseProperty("Ins_Cources")]
    public virtual Course Crs { get; set; }

    [ForeignKey("Ins_Id")]
    [InverseProperty("Ins_Cources")]
    public virtual Instructor Ins { get; set; }
}