// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iti_DB_forms.Models;

[Index("Dept_id", Name = "IX_Instructors_Dept_id")]
public partial class Instructor
{
    [Key]
    public int Ins_Id { get; set; }

    public string Ins_Name { get; set; }

    public string Ins_Degree { get; set; }

    public int? Salary { get; set; }

    public int? Dept_id { get; set; }

    [InverseProperty("Dept_ManegerNavigation")]
    public virtual Department Department { get; set; }

    [ForeignKey("Dept_id")]
    [InverseProperty("Instructors")]
    public virtual Department Dept { get; set; }

    [InverseProperty("Ins")]
    public virtual ICollection<Ins_Cource> Ins_Cources { get; set; } = new List<Ins_Cource>();
}