// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iti_DB_forms.Models;

[Index("Dept_Id", Name = "IX_Students_Dept_Id")]
[Index("St_super", Name = "IX_Students_St_super")]
public partial class Student
{
    [Key]
    public int St_Id { get; set; }

    public string FName { get; set; }

    public string LName { get; set; }

    public string St_Address { get; set; }

    public int? St_Age { get; set; }

    public int? Dept_Id { get; set; }

    public int? St_super { get; set; }

    [ForeignKey("Dept_Id")]
    [InverseProperty("Students")]
    public virtual Department Dept { get; set; }

    [InverseProperty("St_superNavigation")]
    public virtual ICollection<Student> InverseSt_superNavigation { get; set; } = new List<Student>();

    [ForeignKey("St_super")]
    [InverseProperty("InverseSt_superNavigation")]
    public virtual Student St_superNavigation { get; set; }

    [InverseProperty("St")]
    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();
}